services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000" # backend on localhost:3000
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80" # frontend exposed on localhost:5173
    depends_on:
      - backend
    restart: always
